CREATE TABLE IF NOT EXISTS genre(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS mpa(
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS film(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL ,
    description varchar(200),
    release_date date,
    duration int,
    mpa_id INTEGER REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS film_genre(
    film_id INTEGER REFERENCES film (film_id),
    genre_id INTEGER REFERENCES genre (genre_id),
    UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS "user"(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) NOT NULL,
    login varchar(50) NOT NULL,
    name varchar(50),
    birthday date
);

CREATE TABLE IF NOT EXISTS "like"(
    film_id INTEGER REFERENCES film (film_id),
    user_id INTEGER REFERENCES "user" (user_id),
    UNIQUE (film_id,user_id)
);

CREATE TABLE IF NOT EXISTS friend(
    user_id INTEGER REFERENCES "user" (user_id),
    friend_id INTEGER REFERENCES "user" (user_id),
    UNIQUE (user_id,friend_id)
);
